"""
NeuroSync AI — Slide Generator.

Generates PPTX slide decks from extracted concepts using python-pptx.
Each concept gets 1-3 slides (title, content, key takeaways).
"""

from __future__ import annotations

import io
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from loguru import logger


@dataclass
class SlideContent:
    """Content for a single slide."""
    title: str
    bullet_points: list[str] = field(default_factory=list)
    notes: str = ""
    image_path: Optional[str] = None
    layout: str = "bullet"               # bullet, title, image, two_column


@dataclass
class SlideDeck:
    """A collection of slides ready for export."""
    title: str
    slides: list[SlideContent] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def slide_count(self) -> int:
        return len(self.slides)


class SlideGenerator:
    """Generate slide decks from concept maps."""

    def __init__(self, max_slides_per_concept: int = 3,
                 font_size_title: int = 32, font_size_body: int = 18) -> None:
        self.max_per_concept = max_slides_per_concept
        self.font_title = font_size_title
        self.font_body = font_size_body

    def generate(self, concepts: list[Any], title: str = "",
                 summary: str = "", objectives: list[str] | None = None) -> SlideDeck:
        """
        Generate a SlideDeck from extracted concepts.

        Args:
            concepts: List of ExtractedConcept objects.
            title: Presentation title.
            summary: Document summary for intro slide.
            objectives: Learning objectives.

        Returns:
            SlideDeck with all slides populated.
        """
        slides: list[SlideContent] = []

        # Title slide
        slides.append(SlideContent(
            title=title or "Course Content",
            bullet_points=[summary] if summary else [],
            notes="Auto-generated by NeuroSync AI",
            layout="title",
        ))

        # Learning objectives slide
        if objectives:
            slides.append(SlideContent(
                title="Learning Objectives",
                bullet_points=objectives[:8],
                notes="Key outcomes for this lesson",
                layout="bullet",
            ))

        # Concept slides
        for concept in concepts:
            concept_slides = self._concept_to_slides(concept)
            slides.extend(concept_slides[: self.max_per_concept])

        # Summary slide
        concept_names = [c.name for c in concepts[:10]] if concepts else []
        slides.append(SlideContent(
            title="Summary",
            bullet_points=concept_names or ["No concepts extracted"],
            notes="Review of key concepts covered",
            layout="bullet",
        ))

        logger.info("Generated {} slides from {} concepts", len(slides), len(concepts))

        return SlideDeck(
            title=title or "Course Content",
            slides=slides,
            metadata={"concept_count": len(concepts)},
        )

    def _concept_to_slides(self, concept: Any) -> list[SlideContent]:
        """Convert a single concept into 1-3 slides."""
        slides: list[SlideContent] = []

        # Main concept slide
        bullets = []
        if concept.description:
            # Break description into bullet points (split on sentences)
            desc_parts = concept.description.split(". ")
            bullets = [p.strip().rstrip(".") for p in desc_parts if p.strip()][:5]

        if concept.keywords:
            bullets.append(f"Key terms: {', '.join(concept.keywords[:5])}")

        slides.append(SlideContent(
            title=concept.name,
            bullet_points=bullets,
            notes=concept.description,
            layout="bullet",
        ))

        # Difficulty/prerequisites slide (if complex)
        if concept.difficulty in ("hard", "expert") or concept.prerequisites:
            prereq_bullets = []
            if concept.prerequisites:
                prereq_bullets.append(f"Prerequisites: {', '.join(concept.prerequisites[:5])}")
            prereq_bullets.append(f"Difficulty: {concept.difficulty}")
            slides.append(SlideContent(
                title=f"{concept.name} — Details",
                bullet_points=prereq_bullets,
                notes=f"Detailed view of {concept.name}",
                layout="bullet",
            ))

        return slides

    def export_pptx(self, deck: SlideDeck, output_path: str | Path) -> Path:
        """
        Export SlideDeck to a PPTX file.

        Args:
            deck: The slide deck to export.
            output_path: Where to save the PPTX file.

        Returns:
            Path to the created file.
        """
        from pptx import Presentation
        from pptx.util import Inches, Pt

        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        for slide_content in deck.slides:
            layout = prs.slide_layouts[1]  # Title and Content
            if slide_content.layout == "title":
                layout = prs.slide_layouts[0]  # Title Slide

            slide = prs.slides.add_slide(layout)

            # Set title
            if slide.shapes.title:
                slide.shapes.title.text = slide_content.title

            # Set body content
            if slide_content.layout != "title" and len(slide.placeholders) > 1:
                body = slide.placeholders[1]
                tf = body.text_frame
                tf.clear()
                for i, point in enumerate(slide_content.bullet_points):
                    if i == 0:
                        tf.text = point
                    else:
                        p = tf.add_paragraph()
                        p.text = point

            # Add notes
            if slide_content.notes:
                notes_slide = slide.notes_slide
                notes_slide.notes_text_frame.text = slide_content.notes

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        prs.save(str(path))

        logger.info("Exported PPTX: {} ({} slides)", path.name, deck.slide_count)
        return path

    def export_pptx_bytes(self, deck: SlideDeck) -> bytes:
        """Export SlideDeck to PPTX bytes (for in-memory use)."""
        from pptx import Presentation
        from pptx.util import Inches

        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        for slide_content in deck.slides:
            layout = prs.slide_layouts[1]
            if slide_content.layout == "title":
                layout = prs.slide_layouts[0]

            slide = prs.slides.add_slide(layout)
            if slide.shapes.title:
                slide.shapes.title.text = slide_content.title

            if slide_content.layout != "title" and len(slide.placeholders) > 1:
                body = slide.placeholders[1]
                tf = body.text_frame
                tf.clear()
                for i, point in enumerate(slide_content.bullet_points):
                    if i == 0:
                        tf.text = point
                    else:
                        p = tf.add_paragraph()
                        p.text = point

        buf = io.BytesIO()
        prs.save(buf)
        return buf.getvalue()
