"""
NeuroSync AI — Markdown Format Handler.

Generates and exports Markdown-formatted notes from concepts.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class MarkdownOutput:
    """Markdown notes output descriptor."""
    path: str
    title: str
    word_count: int
    section_count: int
    content: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "format": "text/markdown",
            "path": self.path,
            "title": self.title,
            "word_count": self.word_count,
            "section_count": self.section_count,
        }

    def exists(self) -> bool:
        return Path(self.path).exists()


class MarkdownGenerator:
    """Generate Markdown notes from concept maps."""

    def generate(self, concepts: list[Any], title: str = "",
                 summary: str = "", objectives: list[str] | None = None) -> str:
        """
        Generate Markdown content from concepts.

        Args:
            concepts: List of ExtractedConcept objects.
            title: Document title.
            summary: Summary text.
            objectives: Learning objectives.

        Returns:
            Markdown-formatted string.
        """
        lines: list[str] = []

        # Title
        lines.append(f"# {title or 'Course Notes'}")
        lines.append("")

        # Summary
        if summary:
            lines.append(f"> {summary}")
            lines.append("")

        # Learning objectives
        if objectives:
            lines.append("## Learning Objectives")
            lines.append("")
            for obj in objectives:
                lines.append(f"- {obj}")
            lines.append("")

        # Concepts
        lines.append("## Key Concepts")
        lines.append("")

        for i, concept in enumerate(concepts, 1):
            lines.append(f"### {i}. {concept.name}")
            lines.append("")

            if concept.description:
                lines.append(concept.description)
                lines.append("")

            if concept.keywords:
                lines.append(f"**Keywords:** {', '.join(concept.keywords)}")
                lines.append("")

            if concept.difficulty:
                lines.append(f"**Difficulty:** {concept.difficulty}")
                lines.append("")

            if concept.prerequisites:
                lines.append(f"**Prerequisites:** {', '.join(concept.prerequisites)}")
                lines.append("")

            lines.append("---")
            lines.append("")

        # Footer
        lines.append("*Generated by NeuroSync AI*")

        return "\n".join(lines)

    def export(self, content: str, output_path: str | Path) -> MarkdownOutput:
        """Export Markdown content to a file."""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

        word_count = len(content.split())
        section_count = content.count("### ")  # H3 = concept sections

        return MarkdownOutput(
            path=str(path),
            title=path.stem,
            word_count=word_count,
            section_count=section_count,
            content=content,
        )
