"""
NeuroSync AI — Story Format Handler.

Handles story-based explanation output.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class StoryOutput:
    """Story output descriptor."""
    path: str
    title: str
    word_count: int
    segment_count: int
    content: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "format": "text/markdown",
            "path": self.path,
            "title": self.title,
            "word_count": self.word_count,
            "segment_count": self.segment_count,
        }

    def exists(self) -> bool:
        return Path(self.path).exists()


class StoryExporter:
    """Export story content to Markdown format."""

    def export(self, story: Any, output_path: str | Path) -> StoryOutput:
        """
        Export a FullStory to a Markdown file.

        Args:
            story: FullStory object.
            output_path: Where to save the file.

        Returns:
            StoryOutput descriptor.
        """
        lines: list[str] = []

        lines.append(f"# {story.title}")
        lines.append("")
        lines.append("*A Story-Based Explanation*")
        lines.append("")

        if story.introduction:
            lines.append(story.introduction)
            lines.append("")

        for seg in story.segments:
            lines.append(f"## {seg.concept_name}")
            lines.append("")
            lines.append(seg.story_text)
            lines.append("")

            if seg.analogy:
                lines.append(f"**Analogy:** {seg.analogy}")
                lines.append("")
            if seg.moral:
                lines.append(f"**Key Takeaway:** {seg.moral}")
                lines.append("")
            lines.append("---")
            lines.append("")

        if story.conclusion:
            lines.append("## Conclusion")
            lines.append("")
            lines.append(story.conclusion)
            lines.append("")

        lines.append("*Generated by NeuroSync AI*")
        content = "\n".join(lines)

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

        return StoryOutput(
            path=str(path),
            title=story.title,
            word_count=len(content.split()),
            segment_count=len(story.segments),
            content=content,
        )
